# Generated by Django 4.2.7 on 2024-11-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_alter_device_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='bluetooth_identifier',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
