# Generated by Django 4.2.7 on 2024-11-20 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myproject', '0004_device_bluetooth_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicelocation',
            name='device',
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='device_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='devicelocation',
            name='user',
            field=models.ForeignKey(default='',null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
