# Generated by Django 4.2.7 on 2024-11-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0009_alter_device_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='rssi',
            field=models.CharField(),
        ),
    ]
