# Generated by Django 4.2.7 on 2024-11-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0010_alter_device_rssi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='rssi',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='service_uuids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
