# Generated by Django 4.2.7 on 2024-11-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0011_alter_device_rssi_alter_device_service_uuids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='manufacturer_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='service_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='service_uuids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
