# Generated by Django 4.2.7 on 2024-11-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0014_devicelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelocation',
            name='serial_number',
            field=models.IntegerField(null=True),
        ),
    ]
